#!/usr/bin/env bash
#  a Bash script that loops from 1 to 10 and displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iterations
counter=1; 

while [ $counter -le 20 ]; do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
	esac
	((counter++))
done
